# Generated by Django 3.2.9 on 2021-11-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('rg', models.CharField(max_length=255, null=True)),
                ('cpf', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('wage', models.FloatField(default=0)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255, null=True)),
                ('role_description', models.TextField(blank=True, null=True)),
                ('manager', models.BooleanField(default=False)),
            ],
        ),
    ]
